/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rasbot_Main */

#ifndef _Included_rasbot_Main
#define _Included_rasbot_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rasbot_Main
 * Method:    initializeLibrary
 * Signature: ()Vd
 */
JNIEXPORT void JNICALL Java_rasbot_Main_initializeLibrary
  (JNIEnv *, jobject);

/*
 * Class:     rasbot_Main
 * Method:    initializeLeftMotorPd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rasbot_Main_initializeLeftMotorPd
  (JNIEnv *, jobject);

/*
 * Class:     rasbot_Main
 * Method:    initializeRightMotorPd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rasbot_Main_initializeRightMotorPd
  (JNIEnv *, jobject);

/*
 * Class:     rasbot_Main
 * Method:    setLeftMotorRPM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rasbot_Main_setLeftMotorRPM
  (JNIEnv *, jobject, jint);

/*
 * Class:     rasbot_Main
 * Method:    setRightMotorRPM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_rasbot_Main_setRightMotorRPM
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
